In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import scipy.stats as stats

In [4]:
theta_real = 0.35
trials = 4

In [5]:
data = stats.bernoulli.rvs(p=theta_real, size=trials)
data

array([0, 0, 1, 0])

In [33]:
# The number of successes in n (trials) if probability of success is p
data = stats.binom.rvs(n=trials, p=theta_real)
data

4

In [34]:
 # An (numpy) array of length size with each element containing of the number of successes in n trials if probability of success is p
data = stats.binom.rvs(n=trials, p=theta_real, size=3)
data 

array([1, 2, 0])

In [8]:
data = stats.uniform.rvs(loc=0, scale=1, size=trials)
data

array([0.84549923, 0.84283201, 0.68366451, 0.02777986])

In [10]:
mu = 0
sigma = 1
data = stats.norm.rvs(mu, sigma, size=trials)
data

array([-0.04188104,  0.08853094, -0.15005343,  0.45396146])

In [10]:
mu = 0
sigma = 1
data = stats.norm.rvs(mu, sigma, size=trials)
data

array([-0.04188104,  0.08853094, -0.15005343,  0.45396146])